### ISSUE TITLE
What is the License of this project?

### ISSUE THREAD

**Issue by jiixing** [viridia/vortex.web#1]

**Comment by viridia** [comment]
What license would you like? I never bothered adding a license because I was the only person using this :)

**Comment by jiixing** [comment]
Just a standard MIT license would be great. I am learning a lot from this project, and am thinking of upgrading its use of mobx to version 6 so the client can run under vite

**Comment by viridia** [comment]
Done.

**Comment by viridia** [comment]
BTW I would be amenable to the changes you proposed, I've used vite in other projects and I like it quite a bit.

Another potential change would be a port to Electron. I've already done this for my other tool, [sapling](https://github.com/viridia/sapling). While having a web version makes for a nice demo, for someone who is actually creating models and textures for a serious project it is much easier to be able open and save files directly vs. having to download them from the browser.
